### ISSUE TITLE
IntellisenseX - by dot, turn off

### ISSUE THREAD

**Issue by lscheffler** [VFPX/IntelliSenseX#25]
## 📝 Provide detailed reproduction steps (if any)

I do not see how to turn off IntellisenseX  -by dot

1. Install fresh Thor
2. Install IntellisenseX
3. Do not include in  *IntellisenseX - by dot* autostart
4. Turn on  *IntellisenseX - by dot* via menu
5. Test
6. Select *IntellisenseX - by dot* in menu to turn it off

### ✔️ Expected result

The menu should toggle (and, possibly, indicate the status), the *by dot* function should turn off.

### ❌ Actual result

If once on, it stays on

## Comment

I tried *IntellisenseX - by hotkey* in menu. *By dot* still works. Closing and restarting VFP turns *by dot* off, until restarted.

**Comment by Jimrnelson** [comment]
This looks like an easy bug to fix.

Also, it suggest a Thor enhancement, so that the Thor Tools menu indicates if Intellisense By Dot is active.

**Comment by Jimrnelson** [comment]
Fixed in Version 1.25, 2023-12-22

**Comment by lscheffler** [comment]
@Jimrnelson a bit off topic

Guess, it was still not working as expected. I looked a bit deeper.

#### m. on Command Window
"m." works No1 fine in my command window. Only it's not IntellisenseX - it's IntelliSence  - invoking the mem vars. There is a script "m."

#### What IntellisenseX by dot changes
Starting VFP is IntellisenseX by dot off, no var declared. "m." on command window sees nothing, does nothing.

Toggling IntellisenseX by dot on.

"m." on command invokes the ON KEY LABEL -> it declares the `_opemeditor` variable, does not clean up, so the var exists for the script. A Clear All changes nothing, as to expect.

Toggling IntellisenseX by dot off does not release the var - so the script still sees this var. This *looks* like it does not turn off. Or somehow toggling the script on, but not off.

A Clear All removes the var, "m." on command window  sees nothing, does nothing.  (－‸ლ)

#### Conclusio
One should never **use** public vars. Wisdom as old as we can create local vars and parameters. And in special one should clean up ending code. Leaving the environment as found (or better). Also old wisdom. The vars die anyway, but are a pain until then. q.e.d.

:D
